/****** Object: Table [dbo].[tblMovies] ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblMovies](
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Created] DATETIME NOT NULL,
	[Updated] DATETIME NULL,
	[Title] NVARCHAR(100) NOT NULL,
	[Description] NVARCHAR(500) NULL,
	[ReleaseDate] DATETIME NOT NULL,
	[Genre] NVARCHAR(50) NOT NULL,
	[Director] NVARCHAR(100) NOT NULL,
 CONSTRAINT [PK_tblMovies] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, 
       IGNORE_DUP_KEY = OFF, 
       OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF
) ON [PRIMARY]
) ON [PRIMARY]
GO